spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: foliveiradev2024@gmail.com
    password: <GMAIL PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
